### ISSUE TITLE
Add intent to share app 

### ISSUE THREAD

**Issue by cdhiraj40** [anamansari062/Nutrifit#55]
In the left drawer, the share app doesn't work for now.
Here's a [link](https://drive.google.com/file/d/1EBTqvHceNQQAwT2ZfZ-IWwAIHtH5FIz2/view), add an intent to it so users can share the app.

**Comment by Kajal13081** [comment]
I would like to work on this issue. @cdhiraj40 please assign me

**Comment by cdhiraj40** [comment]
hello, @Kajal13081 welcome here,
sure go ahead, here's a [link](https://drive.google.com/file/d/1EBTqvHceNQQAwT2ZfZ-IWwAIHtH5FIz2/view)  :)

**Comment by cdhiraj40** [comment]
any updates @Kajal13081?

**Comment by Kajal13081** [comment]
Yup @cdhiraj40 my end sem just got over. I will complete it in 3-4 days. Sorry for the delay.

**Comment by Kajal13081** [comment]
Hey @cdhiraj40 
I am getting this error. I tried to resolve it, did what they recommended.
![image](https://user-images.githubusercontent.com/80222700/147816786-b8a56536-8057-4933-9f63-370f15507d18.png)

So what I did was, I set up firebase in my project and after rebuilding I got this error.
