### ISSUE TITLE
Add content in About App

### ISSUE THREAD

**Issue by Kajal13081** [anamansari062/Nutrifit#61]
About app screen is empty. I woul like to work on this issue @cdhiraj40 . I would use material design for UI. 
I will get review the written content from you once.

**Comment by cdhiraj40** [comment]
hello @Kajal13081, you are indeed correct. we have talked about this and we actually want to add it. I think you can propose a way the page look or maybe you can wait until we are ready with the about page. maybe you can make PRs for other issues till then? Thanks :)

**Comment by Kajal13081** [comment]
Yes sure. I'll work on other opened issues for now.
